[package]
name = "discord_obs_livebot"
version = "0.0.11"
edition = "2024"

[dependencies]
poise = "0.6.1"
reqwest = { version = "0.12.25", features = ["rustls-tls", "blocking"] }
serde_json = "1.0.145"
serenity = "0.12.4"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
